---
title: "SDS 201: Pre-Course Questionnaire"
date: "Spring 2017"
output: pdf_document
---

### Purpose 
Thank you for completing this questionnaire, which is helpful to me in structuring the course. All information will be kept confidential.  

> Name (nickname):  
> Preferred pronoun (e.g., she/her):  
> Class Year:  
> Major:  
> Email Address:  
> Registration Status (circle one): enrolled/ wait list/ neither  

### Background 
  + Please tell me about your background (e.g. major and area of interest, other activities, significant orgs or athletics):  
  <br>  
  <br>  
  + Please list the three most recent math courses you’ve taken (which may be in high school):  
  <br>  
  + What was your experience like in those courses?  
  <br>  
  <br>  
  + Have you ever taken statistics before (including high school)? If so, please describe:  
  <br>  
  <br>  
  + What are your personal goals for this course?  
  <br>  
  <br>  
  + In which areas of applied statistics are you most interested (e.g. biology, economics, psychology, finance, sociology, etc.) [list as many as you like]?  
  <br>  
  + How strongly do you entertain the notion of working in a quantitative field after graduation (circle one)?  
    1.  not at all 
    2.  hardly ever 
    3.  sometimes 
    4.  often
    5.  OMG, it’s all I think about!   
  <br>  
  + Is there any other information that I should know?  
